### ISSUE TITLE
Currency input directive should handle min or max attributes

### ISSUE THREAD

**Issue by johnsintal** [wealthsimple/ws-directives#22]
Using a regex for `ng-pattern` such as `/^0*[1-9][0-9]*(\.[0-9]+)?|0+\.[0-9]*[1-9][0-9]*$/` is not a good idea, the directive should handle `min` and `max` validators.

**Comment by abejfehr** [comment]
@johnsintal I was going to implement `min` so the pattern can go away...do you think there's a use case for `max` too?

**Comment by abejfehr** [comment]
Fixed in #58
